export const db = "main-stackoverflow"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentCollection = "comments"
export const votesCollection = "votes"
export const questionAttachmentcollection = "question-attachment"
export const userProfileCollection = "user-profiles"